default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 9119
  pool: 5

development:
  <<: *default
  database: mail_database

# test:
#   <<: *default
#   database: my_project_test

production:
  <<: *default
  database: notes
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
